engines:
  duplication:
    enabled: true
    exclude_paths:
      - spec/**/*.rb
    config:
      languages:
        ruby:
          paths:
            - Gemfile
            - Rakefile
            - rubocop-cask.gemspec
            - lib/**/*.rb
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
    - Gemfile
    - Rakefile
    - rubocop-cask.gemspec
    - '**/*.rb'
exclude_paths:
  - vendor/**/*
