engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
    - Gemfile
    - Rakefile
    - rubocop-cask.gemspec
    - '**/*.rb'
exclude_paths:
  - vendor/**/*
