# require: rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*

Metrics/AbcSize:
  Exclude:
    - spec/**/*

# RSpec/DescribeClass:
#   Exclude:
#     - spec/project_spec.rb

# RSpec/VerifiedDoubles:
#   Enabled: true

Style/FileName:
  Exclude:
    - lib/rubocop-cask.rb

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

# to be re-enabled once bbatsov/rubocop#2634 is merged
Style/MutableConstant:
  Enabled: false
