require: rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*

Metrics/AbcSize:
  Exclude:
    - spec/**/*

RSpec/DescribeClass:
  Exclude:
    - spec/project_spec.rb

RSpec/VerifiedDoubles:
  Enabled: true

Style/FileName:
  Exclude:
    - lib/rubocop-cask.rb

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
