# require: rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*

Metrics/AbcSize:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Exclude:
    - lib/rubocop/cop/cask/homepage_matches_url.rb

# RSpec/DescribeClass:
#   Exclude:
#     - spec/project_spec.rb

# RSpec/VerifiedDoubles:
#   Enabled: true

Style/FileName:
  Exclude:
    - lib/rubocop-cask.rb

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
