language: ruby

sudo: false

cache: bundler

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2

before_install:
  - gem update --system --no-ri --no-rdoc
  - gem update --remote bundler

before_script:
  - git config --local user.email "travis@travis.ci"
  - git config --local user.name "Travis CI"

script:
  - bundle exec rake coverage
  - bundle exec overcommit --sign
  - bundle exec overcommit --run

addons:
  code_climate:
    repo_token: 70429dc6dc7d9be22e37c33f1327049305a3106b632f55350632a57a2b3c62b1
