language: ruby

sudo: false

cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2

before_install:
  - gem update --remote bundler
  - git clone --depth 1 git://github.com/bbatsov/rubocop.git vendor/rubocop

before_script:
  - git config --local user.email "travis@travis.ci"
  - git config --local user.name "Travis CI"

script:
  - bundle exec rake coverage
  - bundle exec overcommit --sign
  - bundle exec overcommit --run
